language: node_js

sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest

env:
- TO_TEST=chrome
- TO_TEST=firefox
- TO_TEST=node
- TO_TEST=lint

node_js:
- node
before_install:
- if [ "$TO_TEST" = "chrome" ]; then export CHROME_BIN=/usr/bin/google-chrome; fi
- if [ "$TO_TEST" = "chrome" ] || [ "$TO_TEST" = "firefox" ]; then export DISPLAY=:99.0; fi
- if [ "$TO_TEST" = "chrome" ] || [ "$TO_TEST" = "firefox" ]; then sh -e /etc/init.d/xvfb start; fi
- if [ "$TO_TEST" = "node" ]; then npm install -g jasmine; fi
- if [ "$TO_TEST" = "node" ]; then npm --prefix src/main/platform/nodejs install src/main/platform/nodejs; fi
- if [ "$TO_TEST" = "lint" ]; then npm install -g eslint; fi
- npm install -g gulp
before_script:
- gulp build
script:
- if [ "$TO_TEST" = "chrome" ]; then karma start --single-run --browsers Chrome_travis_ci; fi
- if [ "$TO_TEST" = "firefox" ]; then karma start --single-run --browsers Firefox; fi
- if [ "$TO_TEST" = "node" ]; then jasmine; fi
- if [ "$TO_TEST" = "lint" ]; then eslint src/main src/test *.js; fi

notifications:
  slack:
    secure: dobfBi9oIS4gRFQtfh9m/u3KIR5mDL6rRApKZwL5A77ZHT8qvoZofXacMOkyZUwmtgUQnnkg5hA72iC+ZYyBMjFEjlUlO7Dr3QhWs+Ex/Vy4k/Whk2ep4bBEfhZMv1xBOXjPRKi/NE/bMVdjG3gqs+qNPnc1rfucTMtGTXWJaHVmuFRTGKJXZm/MTDSJAJOpdF6oVJ10DwdkdwZMtuWnpvd2lPvRdk0lyn4TiEyaiAweqwEhqvvXp4LbAl2zfXAhcLQMH8DQzqmTDzdFfAVitARGxvG332RM8C+TEZJjiOkka3Fub2u0ogNHNkxy+9O2ywK+y+yLOj2KEF1tx+prgQQm8FbfJzFQ+KQBt5c1dl2Lf+6OTfwB+LKOm1r2DrAIpJj5i+KHBEvamvTLpdDNGRWt7Or27Kx+jAPUMtmdhSxpnDkGZtNhqinG6oMIKXKjU720QyV775gI+4q5vidBaAH2UU8SxLMJyOj46iel4/nH0g2LbAuoliAW3t0fZHjAwhITEWZDWc6fw0NB2BznXJz8j8IAiPACxbmw2guuZLkF15IpBEn4H04TiXLtRCteVlJ0hVzPjqproWpCj7FDOd2+YlZRh/1L0rB68TJeVa1xp4W5nYM7hTjeYijIAqQQfZAz3GdAOr/FhlVLJDLJsbdtvBmEVPd+dVLZi4eJH4Y=
