name: Build + Test

on:
  - push
  - pull_request

jobs:
  test_node:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '14' ]
    name: Test on node v${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/yarn/
        key: ${{ runner.os }}-yarn-node${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Lint Types
      run: yarn lint-types
    - name: Build
      run: yarn gulp build-web # build-node was already executed during Install step
    - name: Test Node
      run: yarn test-node
    - name: Test Browser
      run: yarn test-browser
